name: Test

on: [workflow_dispatch]

jobs:
  Test-1:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization
        run: echo "hello"
        

      - name: Post Action
        if: always()
        run: |
          echo "post action"
          echo "Workflow Run ID: ${GITHUB_RUN_ID}"
          echo "Workflow Run Number: ${GITHUB_RUN_NUMBER}"
          echo "Workflow Name: ${GITHUB_WORKFLOW}"
          echo "Github Repository: ${GITHUB_REPOSITORY}"
          echo "Job Name: ${GITHUB_JOB}"

          
          
