name: Test

on: [workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Initialization
        run: echo "hello"
        

      - name: Post Action
        if: always()
        run: |
          echo "post action"
          echo "Run ID: ${GITHUB_RUN_ID}"
          echo "Run Number: ${GITHUB_RUN_NUMBER}"
          echo "Actions Name: ${GITHUB_ACTION}"
          echo "Github Repository: ${GITHUB_REPOSITORY}"
          echo "Job Name: ${GITHUB_JOB}"
          
          
